# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "thunderbolt" ]; # thunderbolt on boot
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [
    "amd_iommu=on" # vfio: should be enabled by default, paranoia
    "iommu=pt" # vfio: passthru
    "pci=realloc,assign-busses,hpbussize=0x33" # pcie: allocate hotplug bus numbers for thunderbolt
  ];
  hardware.cpu.amd.updateMicrocode = true;

  # thunderbolt: automatically authorize all devices in initramfs
  boot.initrd.extraUdevRulesCommands = ''
    cat <<EOF >$out/99-thunderbolt.rules
    ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
    EOF
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3bc40ef1-581f-4674-baa3-6c74b33b0f14";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."navi".device = "/dev/disk/by-uuid/2edaba79-5c4d-429a-a9ea-c56716e36f7e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C1A0-8E89";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
